[mypy]

plugins = tensor_plugin/plugin.py
show_traceback = True

allow_untyped_globals = True
allow_redefinition = True
disable_error_code = var-annotated, attr-defined, assignment, union-attr, arg-type, call-overload, call-arg, no-redef, override
check_untyped_defs = True
ignore_missing_imports = True